url: "https://mathayward.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "Mat Hayward" # the name of your site, e.g. ACME Corp.
permalink: /journal/:title
plugins:
  - jekyll-postcss
  - jekyll-minifier
collections:
  photography:
    output: true
    order:
      - iceland.md
      - north-coast-500.md
      - lake-district.md
      - southern-highlands.md
      - tenerife.md
      - skye.md
      - alberta.md
image_base:  https://mathaywarduk.imgix.net/