url: "https://mathayward.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "Mat Hayward" # the name of your site, e.g. ACME Corp.
permalink: /journal/:title
plugins:
  - jekyll-postcss
  - jekyll-minifier
collections:
  photography:
    output: true
    order:
      - lofoten.md
      - iceland.md
      - north-coast-500.md
      - assynt.md
      - lake-district.md
      - southern-highlands.md
      - tenerife.md
      - skye.md
      - alberta.md
  peaks:
    output: true
    order: 
      - fairfield_horseshoe.md
      - loch_long_arrochar.md
      - beinn_each_wild_camp.md
image_base:  https://mathaywarduk.imgix.net/
exclude:
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js